# Generated by Django 3.2.12 on 2022-04-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220422_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requirement',
            old_name='Name',
            new_name='Product_Category',
        ),
        migrations.RemoveField(
            model_name='requirement',
            name='Email',
        ),
        migrations.AddField(
            model_name='requirement',
            name='Discription',
            field=models.TextField(default='', max_length=2000),
            preserve_default=False,
        ),
    ]
