# Generated by Django 3.2.12 on 2022-04-23 13:17

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220422_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_add',
            name='Email',
        ),
        migrations.AlterField(
            model_name='requirement',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=('user', 'Post_Date')),
        ),
    ]
