# Generated by Django 3.2.12 on 2022-04-23 14:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20220423_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_enquiry',
            name='Comp_Name',
        ),
        migrations.RemoveField(
            model_name='product_enquiry',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='product_enquiry',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='product_enquiry',
            name='Post_Date',
        ),
        migrations.RemoveField(
            model_name='product_enquiry',
            name='user',
        ),
        migrations.AddField(
            model_name='product_enquiry',
            name='Product_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='product_enquiry', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product_enquiry',
            name='Sender_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sender_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product_enquiry',
            name='Product_Name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='product_enquiry',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['Product_user', 'Mobile_No']),
        ),
    ]
