# Generated by Django 3.2.12 on 2022-04-23 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20220423_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_enquiry',
            name='Post_Date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
