# Generated by Django 3.2.12 on 2022-05-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20220513_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_add',
            name='Company_Img',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='product_add',
            name='Company_Logo',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='product_add',
            name='Product_Img',
            field=models.ImageField(blank=True, null=True, upload_to='product_img'),
        ),
    ]
