# Generated by Django 3.2.12 on 2022-05-15 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20220514_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_add',
            name='Company_Img',
            field=models.ImageField(blank=True, default='/storage/emulated/0/Download/Fill (6).png', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='product_add',
            name='Company_Logo',
            field=models.ImageField(blank=True, default='/storage/emulated/0/Download/Fill (6).png', null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='product_add',
            name='Product_Img',
            field=models.ImageField(blank=True, default='/storage/emulated/0/Download/Fill (6).png', null=True, upload_to='product_img/'),
        ),
    ]
