# Generated by Django 3.2.12 on 2022-05-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20220515_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Product_Img',
            field=models.ImageField(blank=True, default='/storage/emulated/0/Download/Fill (6).png', null=True, upload_to='product_img/'),
        ),
    ]
