# Generated by Django 3.2.12 on 2022-05-19 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_userprofile_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='Product_Img',
            new_name='Profile_Img',
        ),
    ]
