# Generated by Django 3.2.12 on 2022-06-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20220618_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager_account',
            name='Discription',
            field=models.TextField(blank=True, default=None, help_text='give product name with short use and type of product', null=True),
        ),
        migrations.AlterField(
            model_name='product_add',
            name='Product_Name',
            field=models.CharField(max_length=400),
        ),
    ]
