# Generated by Django 3.2.12 on 2022-09-03 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20220619_1223'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_explore_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField()),
                ('Post_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='product_add',
            name='Product_Category',
            field=models.CharField(choices=[('1', 'Agriculture goods and searvices '), ('2', ' Industrial searvices'), ('3', 'Industerial Plant,Machinery,Equipment'), ('4', 'Consumer Electronics and House Hold Equipment'), ('5', 'Packaging Material suplies and machinery'), ('6', 'Industrial and Enginearing Products sparce '), ('7', 'Building Construct Material, Equipment,Civil Enginearing and Real Estate'), ('8', 'Apperal Clothings and Germent '), ('9', 'Vagitable,Fruits, Grain,Dairy Products and other Grosery Products'), ('10', 'Medical Equipment'), ('11', 'Cemical Dyes and Allied Products'), ('12', 'Macanical Component or Parts '), ('13', 'Scientific,Measuring, Laboratory Products'), ('14', 'Furniture,Furniture Suplies,Furniture Hardware'), ('15', 'Ayurvedic and Herbal Products  '), ('16', 'Sequrity Devices,Safety System and Sequrity Services'), ('17', ' Sports Goods,Games,Toys ,Accessories'), ('18', 'Telecom Products Equipement and Supplies '), ('19', ' Stationary and Paper Products '), ('18', ' Bags,Belts ,Wallets and Accesories '), ('20', 'Stone Marble and Granite Suplies  '), ('21', 'Trade Event Organiser,Event Planner  '), ('22', 'Fertilisers,seeds,plant, Agro Machines'), ('23', 'Polatry and Animal Husbendry  '), ('24', 'Automobile Spare Parts and Accessories'), ('25', 'Computer Softwar,IT Support and Solutions '), ('26', 'Tool,mashine Tool ')], max_length=500),
        ),
    ]
